config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'about'   => 'about#index'
  get 'price'   => 'price#index'
  get 'contact' => 'contact#index'
  get 'admin'   => 'contact#find'

  get 'activities/:cid' => 'contact#activities', as: :activities
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    render 'about/index'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    render 'contact/index'
  end

  def find
    tracking_service = TrackingApi::TrackingService.new host_name
    @contacts = tracking_service.contacts
    render 'contact/list'
  end

  def activities
    tracking_service = TrackingApi::TrackingService.new host_name
    @activities = tracking_service.activities params[:cid]
    render 'contact/activities'
  end

  private

  def host_name
    original_url = request.original_url
    fullpath = request.fullpath
    fullpath = '' if (fullpath == '/')
    original_url.remove fullpath
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render 'home/index'
  end
end

app/controllers/price_controller.rb
class PriceController < ApplicationController
  def index
    render 'price/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<%= render template: "layouts/tracking" %>

<div class="blog-header">
  <h1 class="blog-title">About#Page</h1>
  <p class="lead blog-description">Find me in app/views/about/index.html.erb</p>
</div>

<div class="row">
  <div class="col-sm-10 blog-main">
    <div class="blog-post">
      <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
      <h3>Sub-heading</h3>
      <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
      <pre><code>Example code block</code></pre>
      <p>Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
      <h3>Sub-heading</h3>
      <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <ul>
        <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
        <li>Donec id elit non mi porta gravida at eget metus.</li>
        <li>Nulla vitae elit libero, a pharetra augue.</li>
      </ul>
    </div>
  </div>
</div>

app/views/contact/activities.erb
<div class="blog-header">
  <h1 class="blog-title">Activities#Page</h1>
  <p class="lead blog-description">Find me in app/views/contact/activities.html.erb</p>
</div>

<div class="row">
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Reference</th>
          <th>Activity</th>
          <th>Date Time</th>
        </tr>
      </thead>
      <tbody>
        <% @activities.each do |activity| %>
          <tr>
            <th scope="row"><%= activity["reference"] %></th>
            <td><%= activity["name"] %></td>
            <td><%= activity["dthr"] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/contact/index.html.erb
<%= render template: "layouts/tracking" %>

<div class="blog-header">
  <h1 class="blog-title">Contact#Page</h1>
  <p class="lead blog-description">Find me in app/views/contact/index.html.erb</p>
</div>

<div class="row">
  <div class="col-sm-10 blog-main">
    <%= render template: "layouts/form" %>
  </div>
</div>

app/views/contact/list.html.erb
<div class="blog-header">
  <h1 class="blog-title">Admin#Page</h1>
  <p class="lead blog-description">Find me in app/views/contact/list.html.erb</p>
</div>

<div class="row">
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Email</th>
          <th>Name</th>
          <th>Message</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @contacts.each do |contact| %>
          <tr>
            <th scope="row"><%= contact["email"] %></th>
            <td><%= contact["name"] %></td>
            <td><%= contact["message"] %></td>
            <td><%= link_to "Activities", activities_path(contact["cid"]), target: "_blank" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/index.html.erb
<%= render template: "layouts/tracking" %>

<div class="blog-header">
  <h1 class="blog-title">Home#Page</h1>
  <p class="lead blog-description">Find me in app/views/home/index.html.erb</p>
</div>

<div class="row">
  <div class="col-sm-10 blog-main">
    <div class="blog-post">
      <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
      <h3>Sub-heading</h3>
      <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
      <pre><code>Example code block</code></pre>
      <p>Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
      <h3>Sub-heading</h3>
      <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <ul>
        <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
        <li>Donec id elit non mi porta gravida at eget metus.</li>
        <li>Nulla vitae elit libero, a pharetra augue.</li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracking Pages</title>

    <script src="//code.jquery.com/jquery-2.2.1.min.js"></script>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-50623237-1', 'auto');
      ga('send', 'pageview');

    </script>

    <script>
      var ElTracker=[];(function(){var h='elstage-eltracker.com';var e=document.createElement('script');var p=window===window.parent;if(!p){var r=document.createElement('a');r.href=document.referrer;p=r.hostname.indexOf(h)===-1&&JSON.parse(sessionStorage.getItem('eltracker:editor'))===false;}sessionStorage.setItem('eltracker:editor', !p);e.defer=true;e.type='text/javascript';e.async=true;e.src='//'+h+'/'+(p?"project/cdn/bc2f58b6-3deb-4cdb-a196-34ce41a295d1":"project/cdn/editor/bc2f58b6-3deb-4cdb-a196-34ce41a295d1");var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();
    </script>

  </head>

  <body>
    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item" href="/">Home</a>
          <a class="blog-nav-item" href="/price">Price</a>
          <a class="blog-nav-item" href="/about">About</a>
          <a class="blog-nav-item" href="/contact">Contact</a>
          <a class="btn btn-success btn-sm pull-right" href="/admin" style="margin-top: 5px">Admin</a>
        </nav>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>

    <footer class="blog-footer">
      <p>
        Cras mattis consectetur purus sit amet fermentum. Sed posuere consectetur est at lobortis.
      </p>
    </footer>
  </body>
</html>

app/views/layouts/form.html.erb
<div class="alert alert-danger error-message" style="display:none" role="alert">
  <strong>Oh snap!</strong>
  <span class="msg">Change a few things up and try submitting again.</span>
</div>

<div class="alert alert-success success-message" style="display:none" role="alert">
  <strong>Well done!</strong>
  <span class="msg">You successfully send message. Congratulations!</span>
</div>

<div class="alert alert-warning loading-message" style="display:none" role="alert">
  <strong>Wait!</strong> Wait a little bit
</div>

<%= form_tag("", class: 'tracking-server') do %>
  <div class="form-group">
    <%= label_tag(:name, "Name") %>
    <%= text_field_tag(:name, nil, class: 'form-control') %>
  </div>

  <div class="form-group">
    <%= label_tag(:email, "Email") %>
    <%= email_field_tag(:email, nil, class: 'form-control') %>
  </div>

  <div class="form-group">
    <%= label_tag(:message, "Message") %>
    <%= text_area_tag(:message, nil, class: 'form-control') %>
  </div>

  <%= submit_tag("Send", class: 'btn btn-default') %>
<% end %>

<br />
<br />

app/views/layouts/post.html.erb
<div class="blog-post">
  <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
  <h3>Sub-heading</h3>
  <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
  <pre><code>Example code block</code></pre>
  <p>Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
  <h3>Sub-heading</h3>
  <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
  <ul>
    <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
    <li>Donec id elit non mi porta gravida at eget metus.</li>
    <li>Nulla vitae elit libero, a pharetra augue.</li>
  </ul>
</div>

app/views/layouts/tracking.html.erb
<script>
  (function(act,ref){
    var s='script',w=window,d=document,a=d.createElement(s),m=d.getElementsByTagName(s)[0];a.async=1;
    a.src='//tracking-server.herokuapp.com/release/tracking-analytics.js';m.parentNode.insertBefore(a,m);
    a.onload=function(){trackingAnalytics.sendActivity(act,ref)}
  })('pageview', window.location.pathname);
</script>

app/views/price/index.html.erb
<%= render template: "layouts/tracking" %>

<div class="blog-header">
  <h1 class="blog-title">Price#Page</h1>
  <p class="lead blog-description">Find me in app/views/price/index.html.erb</p>
</div>

<div class="row">
  <div class="col-sm-10 blog-main">
    <div class="blog-post">
      <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
      <h3>Sub-heading</h3>
      <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
      <pre><code>Example code block</code></pre>
      <p>Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
      <h3>Sub-heading</h3>
      <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <ul>
        <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
        <li>Donec id elit non mi porta gravida at eget metus.</li>
        <li>Nulla vitae elit libero, a pharetra augue.</li>
      </ul>
    </div>
  </div>
</div>